repos:
  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v4.3.17
    hooks:
      - id: isort
        language_version: python3
  - repo: https://github.com/ambv/black
    rev: stable
    hooks:
      - id: black
        language_version: python3
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v1.2.3
    hooks:
      - id: flake8
      - id: check-yaml
      - id: check-json
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: "v0.700"
    hooks:
      - id: mypy
        language_version: python3
  - repo: https://github.com/prettier/prettier
    rev: 1.16.4
    hooks:
      - id: prettier
        args: ["--write"]
        files: "(.*\\.json|.*\\.yaml)"
